          CREATE TABLE IF NOT EXISTS HITS (
          ID integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
          APP varchar NOT NULL,
          URI varchar NOT NULL,
          IP varchar NOT NULL,
          HITDATETIME TIMESTAMP NOT NULL,
          CONSTRAINT users_pk PRIMARY KEY (ID)
          );